version: '3.8'

services:
  sonarqube_db:
    image: postgres:${POSTGRES_VERSION}
    container_name: sonarqube_db
    networks:
      - sonarqube_network
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_db:/var/lib/postgresql
    restart: unless-stopped

  sonarqube:
    image: sonarqube:${SONARQUBE_VERSION}
    container_name: sonarqube
    depends_on:
      - sonarqube_db
    networks:
      - sonarqube_network
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/${POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${POSTGRES_USER}
      SONAR_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ports:
      - ${SONARQUBE_PORT}:9000
      - ${SONARQUBE_ELASTICSEARCH_PORT}:9001
    restart: unless-stopped

networks:
  sonarqube_network:
    driver: bridge

volumes:
  postgres_data:
  postgres_db:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp: