name: Build, Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v2

    - name: Set up
      run: Set up complete

    - name: Build
      run: Build complete

    - name: Test
      run: Test complete

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v2

    - name: Set up
      run: Set up complete

    - name: Deploy
      run: Deploy complete